#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" Karotz as an ambient source of light via pykartoz.

Description
-----------

Cycle through the available colors at fading to each color at random. Stop vai
ctrl+c.

"""

from __future__ import division
import time
import random
import karotz as kz

k = kz.Karotz()
periods = [i*1000 for i in range(1, 10)]
while True:
    color = random.choice(kz.COLORS[1:])
    period = random.choice(periods)
    k.led.fade(color=color, period=period)
    time.sleep(period/1000)
